pipeline {
    environment {
        APP_NAME = 'tabular-diabetes-regressor'
        EXPERIMENT_ID = '899851889820856353'
        RUN_ID = 'd196fa50c0224982ab346d8d18934059'
        NAS_NAME = 'gs://zedd-mlruns'
        AR_NAME = 'jo181/bentoml-serving'
    }

    agent {
        docker {
            image 'google/cloud-sdk:alpine'
            args '-u root'
            args '-v $SA_KEY_PATH:/tmp/gcloud/test-key.json'
            }
    }
    stages {
        stage('Authenticate') {
            steps {
                sh 'ls -l /tmp/gcloud'
                sh 'gcloud config configurations create zedd'
                sh 'gcloud config configurations activate zedd'
                sh 'gcloud auth activate-service-account --key-file=/tmp/gcloud/test-key.json'
            }
        }
    }
}