pipeline {
    agent any
    stages {
        stage('Deploy - Staging') {
            steps {
                sh './deploy staging'
                sh './run-smoke-tests'
            }
        }

        stage('Sanity check') {
            steps {
                input "Does the staging environment look ok?"
            }
        }

        stage('Deploy - Production') {
            steps {
                sh './deploy production'
            }
        }
    }
}


/* Requires the Docker Pipeline plugin */
// pipeline {
//     agent { docker { image 'python:3.12.1-alpine3.19' } }
//     stages {
//         stage('build') {
//             steps {
//                 sh 'echo "Hello zedd"'
//             }
//         }
//     }
// }
