pipeline {
    environment {
        APP_NAME = 'tabular-diabetes-regressor'
        EXPERIMENT_ID = '899851889820856353'
        RUN_ID = 'd196fa50c0224982ab346d8d18934059'
        NAS_NAME = 'gs://zedd-mlruns'
        AR_NAME = 'jo181/bentoml-serving'
    }

    agent {
        docker {
            image 'google/cloud-sdk:alpine'
            args '-u root'
            volumes {
                hostPath {
                    path '${SA_KEY_PATH}'
                    type 'File'
                mountPath '/tmp/application_default_credentials.json'
                }
            }
        }
    }
    stages {
        stage('Authenticate') {
            steps {
                sh 'ls -l /tmp'
            }
        }
    }
}